# Generated by Django 5.2.15 on 2026-07-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('project', 'Showcase Project'), ('challenge', 'Challenge Submission'), ('snippet', 'Code Snippet')], default='snippet', max_length=15)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('challenge_id', models.IntegerField(blank=True, null=True)),
                ('challenge_title', models.CharField(blank=True, max_length=255)),
                ('code_snippet', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('github_url', models.URLField(blank=True, default='')),
                ('focus_areas', models.CharField(blank=True, default='general', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_requests', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_review_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('line_ref', models.CharField(blank=True, default='', max_length=50)),
                ('comment_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('issue', 'Issue'), ('praise', 'Praise'), ('question', 'Question')], default='suggestion', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_comments', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_review_comments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='peer_reviews.peerreviewrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
