# Generated by Django 6.0.7 on 2026-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='complexity_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='empirical_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='time_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
