# Generated by Django 6.0.5 on 2026-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('mixed', 'Mixed'), ('rapid_fire', 'Rapid Fire')], max_length=20)),
                ('difficulty', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='mid', max_length=10)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('total_questions', models.IntegerField(default=5)),
                ('score', models.FloatField(blank=True, null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_feedback', models.TextField(blank=True)),
            ],
        ),
    ]
