# Generated by Django 4.2.30 on 2026-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='behavioral_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='eye_contact_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='filler_words_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='posture_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='speaking_pace',
            field=models.IntegerField(default=0),
        ),
    ]
