# Generated by Django 6.0.7 on 2026-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewquestion_behavioral_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='mode',
            field=models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('mixed', 'Mixed'), ('rapid_fire', 'Rapid Fire'), ('boardroom', 'Boardroom')], max_length=20),
        ),
    ]
