# Generated by Django 6.0.7 on 2026-07-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_scheduledtask'),
        ('roadmap', '0002_weektask_cached_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='roadmap_week',
            field=models.ForeignKey(blank=True, help_text='Source roadmap week this task was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='roadmap.roadmapweek'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='topic_label',
            field=models.CharField(blank=True, help_text='Focus area from the roadmap week (e.g. React Hooks)', max_length=120),
        ),
    ]
