# Generated by Django 6.0.5 on 2026-07-05 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('faang_swe', 'FAANG Software Engineer'), ('frontend_dev', 'Frontend Developer'), ('backend_dev', 'Backend Developer'), ('fullstack_dev', 'Full Stack Developer'), ('devops', 'DevOps Engineer'), ('ml_engineer', 'ML/AI Engineer'), ('product', 'Product Manager (Tech)')], default='fullstack_dev', max_length=50)),
                ('summary', models.TextField(blank=True, help_text='AI-generated roadmap overview')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('focus_area', models.CharField(max_length=100)),
                ('weakness_reason', models.TextField(blank=True)),
                ('xp_goal', models.IntegerField(default=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='roadmap.learningpath')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='WeekTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('challenge', 'Challenge'), ('interview', 'Interview Session'), ('study', 'Study Topic')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('challenge_id', models.IntegerField(blank=True, null=True)),
                ('interview_mode', models.CharField(blank=True, max_length=20)),
                ('interview_difficulty', models.CharField(blank=True, max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.roadmapweek')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
