# Generated by Django 6.0.5 on 2026-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weektask',
            name='cached_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
