# Generated by Django 5.2.15 on 2026-07-25 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_mastery', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recurring_mistakes', models.JSONField(blank=True, default=list)),
                ('interview_stats', models.JSONField(blank=True, default=dict)),
                ('career_goals', models.JSONField(blank=True, default=dict)),
                ('learning_habits', models.JSONField(blank=True, default=dict)),
                ('activity_log', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='Developer profile initialized. AI Memory Engine is actively tracking your learning journey across all modules.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
